### ISSUE TITLE
DXA Resolver fails silently when adding items with circular references

### ISSUE THREAD

**Issue by kunalshetye** [RWS/dxa-content-management#26]
I've already fixed the issue and the pull request for this fix can be found here: https://github.com/sdl/dxa-content-management/pull/25

_DXA Custom Resolver initialised with recurse depth -1
DXA Custom Resolver started...
Loading global app data:
Found configuration for custom resolver in global app data. Attempting to parse.
Found configuration using XElement appData type.
xml=<Configuration xmlns:dcr="http://www.sdltridion.com/2017/DXACustomResolver"><dcr:RecurseDepth>1</dcr:RecurseDepth></Configuration>
Found RecurseDepth value of '1'.
Using _maxRecurseDepth=1
Gathering linked components for component [MASTER] Embargo_ABC
Gathering linked components for component [MASTER] Embargo_DEF
Gathering linked components for component [MASTER] style-sheet.css
Gathering linked components for component remove-spacing-top.css
Gathering linked components for component remove-spacing-bottom.css
Gathering linked components for component remove-spacing.css
Gathering linked components for component remove-tint.css
Gathering linked components for component reduce-tint.css
Gathering linked components for component [TRANSLATE] Code_In Page Navigation My Product
Gathering linked components for component [TRANSLATE] Text_For My Product._

**Stacktrace:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary``2.Insert(TKey key, TValue value, Boolean add)
   at Sdl.Web.DXAResolver.Resolver.ResolveItem(IdentifiableObject item, ComponentTemplate template, HashSet``1 resolved, Int32 recurseLevel)
   at Sdl.Web.DXAResolver.Resolver.Resolve(IdentifiableObject item, ResolveInstruction instruction, PublishContext context, ISet`1 resolvedItems)**

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12800
